### ISSUE TITLE
Individual Data Usage

### ISSUE THREAD

**Issue by coldrider1** [SIU-CS/DataDam-production#4]
As a user, I want to see individual applications’ data usage so that I can better understand which
applications are using more data.
1. Data Dam will be able to record the individual application data usage. 
2. The user will be able to access the individual application data usage via the Individual Values option. 
3. The recording of the individual application data usage must conform to other constraints set by the user.

**Comment by amiangshu** [comment]
@coldrider1 : please add estimates to your stories.
